{% set name = "logfire" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logfire-{{ version }}.tar.gz
  sha256: 82971d94dade325ad40b2c0fc830caad8459a0b60a63591af68598b10c6b3f5d

build:
  entry_points:
    - logfire = logfire.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - opentelemetry-sdk >=1.21.0
    - opentelemetry-exporter-otlp-proto-http >=1.21.0
    - opentelemetry-instrumentation >=0.41b0
    - rich >=13.4.2
    - protobuf >=4.23.4
    - typing-extensions >=4.0.0
    - tomli >=2.0.1

test:
  imports:
    - logfire
  commands:
    - pip check
    - logfire --help
  requires:
    - pip

about:
  home: https://pypi.org/project/logfire/
  summary: Coming soon...
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Kludex
    - samuelcolvin
