{% set name = "logfire" %}
{% set version = "0.45.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logfire-{{ version }}.tar.gz
  sha256: f9b965d2e1fd9a0bfff028e0b4d69e58f1eb662340f33b5d5f8ff1c89ca1785f

build:
  entry_points:
    - logfire = logfire.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - executing >=2.0.1
    - python >=3.8
    - opentelemetry-sdk >=1.21.0
    - opentelemetry-exporter-otlp-proto-http >=1.21.0
    - opentelemetry-instrumentation >=0.41b0
    - rich >=13.4.2
    - protobuf >=4.23.4
    - typing-extensions >=4.1.0
    - tomli >=2.0.1

test:
  imports:
    - logfire
  commands:
    - pip check
    - logfire --help
  requires:
    - pip

about:
  home: https://github.com/pydantic/logfire
  dev_url: https://github.com/pydantic/logfire
  doc_url: https://docs.pydantic.dev/logfire
  summary: The best Python observability tool! 🪵🔥
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Kludex
    - samuelcolvin
