{% set name = "logfire" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/logfire-{{ version }}.tar.gz
  sha256: 93b11d94ad1a19a8bfc1fd97b40ecc3c919a3edc6a5e51cb2a153e64cd04aa9e

build:
  entry_points:
    - logfire = logfire.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - typing_extensions >=4.1.0
    - executing >=2.0.1
    - python >=3.8
    - opentelemetry-sdk >=1.21.0,<1.31.0
    - opentelemetry-exporter-otlp-proto-http >=1.21.0,<1.31.0
    - opentelemetry-instrumentation >=0.41b0
    - rich >=13.4.2
    - protobuf >=4.23.4
    - typing-extensions >=4.1.0
    - tomli >=2.0.1

test:
  imports:
    - logfire
  commands:
    - pip check
    - logfire --help
  requires:
    - pip

about:
  home: https://github.com/pydantic/logfire
  dev_url: https://github.com/pydantic/logfire
  doc_url: https://docs.pydantic.dev/logfire
  summary: The best Python observability tool! 🪵🔥
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Kludex
    - samuelcolvin
